name: Build macOS App

on:
  push:
    branches: [ gui-version ]
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build standalone app
        run: |
          pyinstaller --onefile --windowed renamer_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Renamer-macOS
          path: dist/renamer_gui

